const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.GestureRecognizer,
		C3.Plugins.Browser,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.GestureRecognizer.Acts.AddGesture,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.GestureRecognizer.Acts.AddPoint,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.GestureRecognizer.Acts.RecognizeGesture,
		C3.Plugins.GestureRecognizer.Cnds.OnAnyGesture,
		C3.Plugins.GestureRecognizer.Exps.GestureName,
		C3.Plugins.GestureRecognizer.Cnds.isGesture,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.SetY
	];
};
self.C3_JsPropNameTable = [
	{Pin: 0},
	{lvl_1: 0},
	{lvl_2: 0},
	{lvl_3: 0},
	{Bottom: 0},
	{Btn_Livelli: 0},
	{pre_level_design: 0},
	{btn_settings: 0},
	{DragDrop: 0},
	{TiledBackground: 0},
	{spr_countdown007: 0},
	{spr_resolve_txt: 0},
	{spr_resolve_txt_cpu: 0},
	{spr_nocharge: 0},
	{Background: 0},
	{Tween: 0},
	{Camera_cpu: 0},
	{Camera_player: 0},
	{Countdown: 0},
	{Debug_Speed: 0},
	{Result: 0},
	{spr_CPU: 0},
	{spr_Player: 0},
	{Text_CPUMove: 0},
	{Text_PlayerMove: 0},
	{Touch: 0},
	{MossePlayer: 0},
	{GestureRecognizer: 0},
	{Camera_center: 0},
	{Browser: 0},
	{Particles: 0},
	{Sine: 0},
	{spr_luce: 0},
	{fire_spr: 0},
	{fire_spr2: 0},
	{BladeSmoother: 0},
	{Blade: 0},
	{Fade: 0},
	{TurnState: 0},
	{PlayerMove: 0},
	{Player_Cariche: 0},
	{CPU_Livello: 0},
	{CPUMove: 0},
	{CPU_Cariche: 0},
	{DebugRecognize: 0},
	{NoChargeTextSprite: 0},
	{PreviousX: 0},
	{PreviousY: 0},
	{player_spawned: 0},
	{cpu_spawned: 0},
	{NumCarica: 0},
	{NumSpara: 0},
	{oneTimeAnimated: 0},
	{oneTimeAnimatedCPU: 0}
];

self.InstanceType = {
	lvl_1: class extends self.ISpriteInstance {},
	lvl_2: class extends self.ISpriteInstance {},
	lvl_3: class extends self.ISpriteInstance {},
	Bottom: class extends self.ISpriteInstance {},
	Btn_Livelli: class extends self.ISpriteInstance {},
	pre_level_design: class extends self.ISpriteInstance {},
	btn_settings: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	spr_countdown007: class extends self.ISpriteInstance {},
	spr_resolve_txt: class extends self.ISpriteInstance {},
	spr_resolve_txt_cpu: class extends self.ISpriteInstance {},
	spr_nocharge: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Camera_cpu: class extends self.ISpriteInstance {},
	Camera_player: class extends self.ISpriteInstance {},
	Countdown: class extends self.ITextInstance {},
	Debug_Speed: class extends self.ITextInstance {},
	Result: class extends self.ITextInstance {},
	spr_CPU: class extends self.ISpriteInstance {},
	spr_Player: class extends self.ISpriteInstance {},
	Text_CPUMove: class extends self.ITextInstance {},
	Text_PlayerMove: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	MossePlayer: class extends self.IArrayInstance {},
	GestureRecognizer: class extends self.IInstance {},
	Camera_center: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	spr_luce: class extends self.ISpriteInstance {},
	fire_spr: class extends self.ISpriteInstance {},
	fire_spr2: class extends self.ISpriteInstance {},
	BladeSmoother: class extends self.ISpriteInstance {},
	Blade: class extends self.ISpriteInstance {},
	Fade: class extends self.ITiledBackgroundInstance {}
}